2024-09-11 17:33:00.571355: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-11 17:33:00.571359: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-11 17:33:00.571378: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-11 17:33:00.571359: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-11 17:33:00.571358: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-11 17:33:00.695971: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-11 17:33:00.695974: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-11 17:33:00.695943: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-11 17:33:00.696000: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-11 17:33:00.696009: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-11 17:33:00.734951: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-11 17:33:00.734952: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-11 17:33:00.734955: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-11 17:33:00.734956: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-11 17:33:00.734951: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-11 17:33:00.984715: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-11 17:33:00.984699: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-11 17:33:00.984699: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-11 17:33:00.984699: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-11 17:33:00.984699: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-11 17:33:04.014108: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-09-11 17:33:04.014108: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-09-11 17:33:04.014110: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-09-11 17:33:04.014110: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-09-11 17:33:04.014107: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[flash33:mpi_rank_0][MPID_Init] [Performance Suggestion]: Application has requested for multi-thread capability. If allocating memory from different pthreads/OpenMP threads, please consider setting MV2_USE_ALIGNED_ALLOC=1 for improved performance.
Use MV2_USE_THREAD_WARNING=0 to suppress this error message.
2024-09-11 17:33:19.316969: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2343] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-09-11 17:33:19.316974: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2343] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-09-11 17:33:19.316974: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2343] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-09-11 17:33:19.316974: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2343] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-09-11 17:33:19.316974: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2343] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "/g/g90/dhakal1/All/ice4hpc/src/driver.py", line 161, in <module>
    obj(os.getcwd()+args.yaml, args.target_app, qrrp_p, rcrp_p, qrrp_X_train, qrrp_y_train, qrrp_tar_x_test, qrrp_tar_y_test, rcrp_X_train, rcrp_y_train,rcrp_tar_x_test, rcrp_tar_y_test, rank)
  File "/g/g90/dhakal1/All/ice4hpc/src/one_out.py", line 53, in __call__
    mse0, mape0, mse1, mape1 = obj(config_yaml, A_X_train, A_Y_train, A_tar_x_scaled, A_tar_y_scaled, B_X_train, B_Y_train, B_tar_x_scaled, B_tar_y_scaled)
  File "/g/g90/dhakal1/All/ice4hpc/src/AdaBoost.py", line 52, in __call__
    A_tar_x_scaled = imputer_A.transform(A_tar_x_scaled)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 570, in transform
Traceback (most recent call last):
  File "/g/g90/dhakal1/All/ice4hpc/src/driver.py", line 161, in <module>
    obj(os.getcwd()+args.yaml, args.target_app, qrrp_p, rcrp_p, qrrp_X_train, qrrp_y_train, qrrp_tar_x_test, qrrp_tar_y_test, rcrp_X_train, rcrp_y_train,rcrp_tar_x_test, rcrp_tar_y_test, rank)
  File "/g/g90/dhakal1/All/ice4hpc/src/one_out.py", line 53, in __call__
    mse0, mape0, mse1, mape1 = obj(config_yaml, A_X_train, A_Y_train, A_tar_x_scaled, A_tar_y_scaled, B_X_train, B_Y_train, B_tar_x_scaled, B_tar_y_scaled)
  File "/g/g90/dhakal1/All/ice4hpc/src/AdaBoost.py", line 52, in __call__
    A_tar_x_scaled = imputer_A.transform(A_tar_x_scaled)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
Traceback (most recent call last):
  File "/g/g90/dhakal1/All/ice4hpc/src/driver.py", line 161, in <module>
    obj(os.getcwd()+args.yaml, args.target_app, qrrp_p, rcrp_p, qrrp_X_train, qrrp_y_train, qrrp_tar_x_test, qrrp_tar_y_test, rcrp_X_train, rcrp_y_train,rcrp_tar_x_test, rcrp_tar_y_test, rank)
  File "/g/g90/dhakal1/All/ice4hpc/src/one_out.py", line 53, in __call__
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 570, in transform
    X = self._validate_input(X, in_fit=False)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 350, in _validate_input
    mse0, mape0, mse1, mape1 = obj(config_yaml, A_X_train, A_Y_train, A_tar_x_scaled, A_tar_y_scaled, B_X_train, B_Y_train, B_tar_x_scaled, B_tar_y_scaled)
  File "/g/g90/dhakal1/All/ice4hpc/src/AdaBoost.py", line 52, in __call__
    X = self._validate_input(X, in_fit=False)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 350, in _validate_input
    raise ve
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 332, in _validate_input
    A_tar_x_scaled = imputer_A.transform(A_tar_x_scaled)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
    raise ve
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 332, in _validate_input
    X = self._validate_data(
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/base.py", line 654, in _validate_data
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 570, in transform
    X = self._validate_data(
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/base.py", line 654, in _validate_data
    X = self._validate_input(X, in_fit=False)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 350, in _validate_input
    raise ve
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 332, in _validate_input
    X = self._validate_data(
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/base.py", line 654, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/base.py", line 443, in _check_n_features
    self._check_n_features(X, reset=reset)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/base.py", line 443, in _check_n_features
    self._check_n_features(X, reset=reset)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/base.py", line 443, in _check_n_features
    raise ValueError(
    raise ValueError(
ValueError: X has 30 features, but SimpleImputer is expecting 43 features as input.
ValueError: X has 30 features, but SimpleImputer is expecting 43 features as input.
    raise ValueError(
ValueError: X has 30 features, but SimpleImputer is expecting 43 features as input.
Traceback (most recent call last):
  File "/g/g90/dhakal1/All/ice4hpc/src/driver.py", line 161, in <module>
    obj(os.getcwd()+args.yaml, args.target_app, qrrp_p, rcrp_p, qrrp_X_train, qrrp_y_train, qrrp_tar_x_test, qrrp_tar_y_test, rcrp_X_train, rcrp_y_train,rcrp_tar_x_test, rcrp_tar_y_test, rank)
  File "/g/g90/dhakal1/All/ice4hpc/src/one_out.py", line 53, in __call__
Traceback (most recent call last):
  File "/g/g90/dhakal1/All/ice4hpc/src/driver.py", line 161, in <module>
    mse0, mape0, mse1, mape1 = obj(config_yaml, A_X_train, A_Y_train, A_tar_x_scaled, A_tar_y_scaled, B_X_train, B_Y_train, B_tar_x_scaled, B_tar_y_scaled)
  File "/g/g90/dhakal1/All/ice4hpc/src/AdaBoost.py", line 52, in __call__
    A_tar_x_scaled = imputer_A.transform(A_tar_x_scaled)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
    obj(os.getcwd()+args.yaml, args.target_app, qrrp_p, rcrp_p, qrrp_X_train, qrrp_y_train, qrrp_tar_x_test, qrrp_tar_y_test, rcrp_X_train, rcrp_y_train,rcrp_tar_x_test, rcrp_tar_y_test, rank)
  File "/g/g90/dhakal1/All/ice4hpc/src/one_out.py", line 53, in __call__
    mse0, mape0, mse1, mape1 = obj(config_yaml, A_X_train, A_Y_train, A_tar_x_scaled, A_tar_y_scaled, B_X_train, B_Y_train, B_tar_x_scaled, B_tar_y_scaled)
  File "/g/g90/dhakal1/All/ice4hpc/src/AdaBoost.py", line 52, in __call__
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 570, in transform
    A_tar_x_scaled = imputer_A.transform(A_tar_x_scaled)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
    X = self._validate_input(X, in_fit=False)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 350, in _validate_input
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 570, in transform
    raise ve
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 332, in _validate_input
    X = self._validate_input(X, in_fit=False)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 350, in _validate_input
    X = self._validate_data(
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/base.py", line 654, in _validate_data
    raise ve
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/impute/_base.py", line 332, in _validate_input
    self._check_n_features(X, reset=reset)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/base.py", line 443, in _check_n_features
    X = self._validate_data(
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/base.py", line 654, in _validate_data
    raise ValueError(
ValueError: X has 30 features, but SimpleImputer is expecting 43 features as input.
    self._check_n_features(X, reset=reset)
  File "/g/g90/dhakal1/All/dev/lib/python3.9/site-packages/sklearn/base.py", line 443, in _check_n_features
    raise ValueError(
ValueError: X has 30 features, but SimpleImputer is expecting 43 features as input.
srun: error: flash33: tasks 0-4: Exited with exit code 1
